import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import datetime
import uuid
import asyncio
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SERVICE_ACCOUNT_FILE = os.path.join(os.path.dirname(__file__), 'service_account.json')
TOKEN_FILE = os.path.join(os.path.dirname(__file__), 'token.json')
CALENDAR_SCOPES = [
    'https://www.googleapis.com/auth/calendar',
    'https://www.googleapis.com/auth/gmail.send',
    'https://www.googleapis.com/auth/meetings.space.created',
]


def _get_calendar_service():
    """
    Returns a Google Calendar service using OAuth token if available,
    otherwise falls back to Service Account.
    """
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, CALENDAR_SCOPES)
        return build('calendar', 'v3', credentials=creds)
    else:
        creds = service_account.Credentials.from_service_account_file(
            SERVICE_ACCOUNT_FILE, scopes=CALENDAR_SCOPES
        )
        return build('calendar', 'v3', credentials=creds)


def generate_meet_link(date_str: str, time_str: str, attendee_emails: list = None) -> str:
    """
    Creates a Google Calendar event with a Google Meet conference link.
    Requires token.json (generated by running auth_calendar.py once).
    Returns the Google Meet hangout link, or None if creation fails.

    The account whose token.json is used becomes the organizer (auto-joins
    as host with no waiting room). All other attendees get responseStatus
    'accepted' so Google Meet recognises them as confirmed invited guests.
    The organizer email is excluded from attendees to avoid a self-invite.
    """
    try:
        service = _get_calendar_service()

        dt_str = f"{date_str} {time_str}"
        dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d %I:%M %p")
        start_time = dt.isoformat()
        end_time = (dt + datetime.timedelta(hours=1)).isoformat()

        # Exclude the organizer (token.json account) from attendees
        # to avoid a redundant self-invite.
        organizer_email = os.getenv("GMAIL_USER", "").lower()
        filtered_emails = [
            e for e in (attendee_emails or [])
            if e.lower() != organizer_email
        ]

        # responseStatus='accepted' marks guests as confirmed invitees,
        # which is the best signal we can send via the Calendar API.
        attendees = [
            {'email': e, 'responseStatus': 'accepted'}
            for e in filtered_emails
        ]

        event = {
            'summary': 'Rehab 5 Consultation',
            'location': 'Online - Google Meet',
            'description': 'Your scheduled consultation with Rehab 5.',
            'start': {'dateTime': start_time, 'timeZone': 'Asia/Dubai'},
            'end': {'dateTime': end_time, 'timeZone': 'Asia/Dubai'},
            'conferenceData': {
                'createRequest': {
                    'requestId': uuid.uuid4().hex,
                    'conferenceSolutionKey': {'type': 'hangoutsMeet'}
                }
            },
            'attendees': attendees,
            'guestsCanModify': True,
            'guestsCanInviteOthers': True,
            'guestsCanSeeOtherGuests': True,
            'visibility': 'public',
            'anyoneCanAddSelf': True,
            'status': 'confirmed',
        }

        event_result = service.events().insert(
            calendarId='primary',
            body=event,
            conferenceDataVersion=1,
            sendUpdates='all'   # sends Google Calendar invite emails
        ).execute()

        meet_link = event_result.get('hangoutLink')

        # Attempt to disable host management on the newly created space
        # via the Meet REST API so no one is stuck in a waiting room.
        if meet_link:
            try:
                _disable_host_management(meet_link)
            except Exception as meet_err:
                print(f"[Meet API] Could not disable host management (non-fatal): {meet_err}")

        return meet_link

    except Exception as e:
        print(f"Google Meet event creation failed: {e}")
        return None


def _disable_host_management(meet_link: str):
    """
    Uses the Google Meet REST API to set the space access to OPEN
    so no participant ever sees 'waiting for host to admit you'.
    meet_link example: https://meet.google.com/abc-defg-hij
    """
    import json as _json
    import urllib.request as urlreq

    # Extract the meeting code from the link
    code = meet_link.rstrip('/').split('/')[-1]  # e.g. 'abc-defg-hij'

    creds = Credentials.from_authorized_user_file(TOKEN_FILE, CALENDAR_SCOPES)
    if creds.expired and creds.refresh_token:
        from google.auth.transport.requests import Request
        creds.refresh(Request())

    # PATCH the space to set access type to OPEN (no waiting room)
    url = f"https://meet.googleapis.com/v2/spaces/{code}"
    payload = _json.dumps({
        "config": {
            "accessType": "OPEN",
            "entryPointAccess": "ALL"
        }
    }).encode()

    req = urlreq.Request(
        url,
        data=payload,
        method='PATCH',
        headers={
            'Authorization': f'Bearer {creds.token}',
            'Content-Type': 'application/json',
            'X-Goog-FieldMask': 'config.accessType,config.entryPointAccess'
        }
    )
    with urlreq.urlopen(req) as resp:
        result = _json.loads(resp.read())
        print(f"[Meet API] Space updated: accessType={result.get('config', {}).get('accessType')}")
        return False


def create_calendar_event(date_str: str, time_str: str, meet_link: str) -> bool:
    """
    Creates a plain Google Calendar event with the meet_link in the description.
    Used as fallback.
    """
    try:
        service = _get_calendar_service()

        dt_str = f"{date_str} {time_str}"
        dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d %I:%M %p")
        start_time = dt.isoformat()
        end_time = (dt + datetime.timedelta(hours=1)).isoformat()

        event = {
            'summary': 'Rehab 5 Consultation',
            'location': meet_link,
            'description': f'Join the consultation: {meet_link}',
            'start': {'dateTime': start_time, 'timeZone': 'Asia/Dubai'},
            'end': {'dateTime': end_time, 'timeZone': 'Asia/Dubai'},
        }

        service.events().insert(calendarId='primary', body=event).execute()
        return True

    except Exception as e:
        print(f"Calendar event creation failed: {e}")
        return False


def send_email(to_email: str, subject: str, body: str) -> bool:
    """
    Sends an email via the Gmail API (HTTPS) instead of SMTP.
    Uses the existing token.json OAuth credentials.
    """
    sender_email = os.getenv("GMAIL_USER")
    if not sender_email:
        print("GMAIL_USER not found in env")
        return False

    try:
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, CALENDAR_SCOPES)
        service = build('gmail', 'v1', credentials=creds)

        msg = MIMEMultipart("alternative")
        msg['From'] = f"Rehab 5 <{sender_email}>"
        msg['To'] = to_email
        msg['Reply-To'] = sender_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'html'))

        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        service.users().messages().send(
            userId='me',
            body={'raw': raw}
        ).execute()

        print(f"Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False

def get_doctor_email_template(booking_date: str, booking_time: str, patient_name: str, patient_email: str, patient_phone: str, meet_link: str) -> str:
    """Returns the HTML email body to be sent to the doctor."""
    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>New Consultation Scheduled</title>
</head>
<body style="margin:0;padding:0;background-color:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr>
      <td align="center" style="padding: 0 10px;">
        <table cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);text-align:left;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1e3a8a,#3b82f6);padding:40px 40px 32px;text-align:center;">
              <h1 style="color:#ffffff;margin:0;font-size:26px;font-weight:700;letter-spacing:0.5px;">New Patient Consultation</h1>
              <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:14px;">A new appointment has been scheduled</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:40px;">
              <p style="color:#374151;font-size:15px;margin:0 0 24px;">Hello Doctor,<br/><br/>
              A new consultation has been booked on Rehab 5. Please find the patient details below.</p>

              <!-- Patient Details Card -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border-radius:12px;border:1px solid #e2e8f0;margin-bottom:28px;">
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">👤 Patient Name</td>
                        <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">{patient_name}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">📧 Email</td>
                         <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;"><a href="mailto:{patient_email}" style="color:#3b82f6;text-decoration:none;">{patient_email}</a></td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">📞 Phone</td>
                        <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">{patient_phone}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">📅 Date & Time</td>
                        <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">{booking_date} at {booking_time} (UAE)</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- CTA Button -->
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:8px 0 32px;">
                    <a href="{meet_link}" target="_blank"
                       style="display:inline-block;background:linear-gradient(135deg,#1e3a8a,#3b82f6);color:#ffffff;text-decoration:none;font-size:16px;font-weight:700;padding:16px 40px;border-radius:50px;letter-spacing:0.5px;box-shadow:0 4px 14px rgba(59,130,246,0.4);">
                      🎥 &nbsp; Join Google Meet
                    </a>
                  </td>
                </tr>
              </table>
              <p style="color:#6b7280;font-size:13px;text-align:center;word-break:break-all;margin:0 0 32px;">{meet_link}</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

def get_patient_email_template(patient_name: str, booking_date: str, booking_time: str, meet_link: str) -> str:
    """Returns the responsive HTML email body to be sent to the patient."""
    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Booking Confirmed</title>
</head>
<body style="margin:0;padding:0;background-color:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr>
      <td align="center" style="padding: 0 10px;">
        <table cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);text-align:left;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#0f766e,#14b8a6);padding:40px 40px 32px;text-align:center;">
              <div style="display:inline-block;background:rgba(255,255,255,0.15);border-radius:12px;padding:10px 24px;margin-bottom:16px;">
                <span style="color:#ffffff;font-size:22px;font-weight:800;letter-spacing:2px;">REHAB 5</span>
              </div>
              <h1 style="color:#ffffff;margin:0;font-size:26px;font-weight:700;letter-spacing:0.5px;">Booking Confirmed</h1>
              <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:14px;">Your consultation has been successfully scheduled</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:40px;">
              <p style="color:#374151;font-size:15px;margin:0 0 24px;">Hi {patient_name} 👋,<br/><br/>
              Great news! Your appointment with <strong>Rehab 5</strong> has been confirmed. We look forward to seeing you.</p>

              <!-- Details Card -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border-radius:12px;border:1px solid #e2e8f0;margin-bottom:28px;">
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">📅 Date</td>
                        <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">{booking_date}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">🕐 Time</td>
                         <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">{booking_time} (UAE Time / GST)</td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 24px;">
                    <table width="100%">
                      <tr>
                        <td style="color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;width:30%;vertical-align:top;padding-right:10px;">🎥 Meeting</td>
                        <td style="color:#111827;font-size:15px;font-weight:600;word-break:break-word;">Online Video Call</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- CTA Button -->
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:8px 0 32px;">
                    <a href="{meet_link}" target="_blank"
                       style="display:inline-block;background:linear-gradient(135deg,#0f766e,#14b8a6);color:#ffffff;text-decoration:none;font-size:16px;font-weight:700;padding:16px 40px;border-radius:50px;letter-spacing:0.5px;box-shadow:0 4px 14px rgba(20,184,166,0.4);">
                      🎥 &nbsp; Join Video Consultation
                    </a>
                  </td>
                </tr>
              </table>
              <p style="color:#6b7280;font-size:13px;text-align:center;margin:0 0 8px;">Or copy this link to your browser:</p>
              <p style="color:#0f766e;font-size:13px;text-align:center;word-break:break-all;margin:0 0 32px;"><a href="{meet_link}" style="color:#0f766e;">{meet_link}</a></p>
              <!-- Reminder -->
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="background:#fffbeb;border-left:4px solid #f59e0b;border-radius:0 8px 8px 0;padding:14px 18px;">
                    <p style="margin:0;color:#92400e;font-size:13px;">⏰ <strong>Reminder:</strong> Please join the meeting 5 minutes before your scheduled time.</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#f8fafc;padding:24px 40px;border-top:1px solid #e2e8f0;text-align:center;">
              <p style="color:#9ca3af;font-size:12px;margin:0 0 4px;">© 2025 Rehab 5. All rights reserved.</p>
              <p style="color:#9ca3af;font-size:12px;margin:0;">If you need to reschedule, please contact us at <a href="mailto:contactsoocher@gmail.com" style="color:#14b8a6;text-decoration:none;">contactsoocher@gmail.com</a></p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

async def send_emails_concurrently(patient_email: str, patient_subject: str, patient_body: str, doctor_email: str, doctor_subject: str, doctor_body: str) -> bool:
    """Dispatches the patient and doctor emails concurrently using asyncio threads."""
    try:
        results = await asyncio.gather(
            asyncio.to_thread(send_email, patient_email, patient_subject, patient_body),
            asyncio.to_thread(send_email, doctor_email, doctor_subject, doctor_body),
            return_exceptions=True
        )
        # We can handle or log exceptions separately if required, but we return True if the patient email succeeded
        patient_sent = results[0]
        doctor_sent = results[1]
        
        if isinstance(doctor_sent, Exception):
            print(f"Doctor email thread exception: {doctor_sent}")
        
        if isinstance(patient_sent, Exception):
            print(f"Patient email thread exception: {patient_sent}")
            return False
            
        return patient_sent
    except Exception as e:
        print(f"Fatal error during concurrent email dispatch: {e}")
        return False
