import type { ConsultationRecord } from "@/doctor/types/consultation";

export const TODAY_CONSULTATIONS: ConsultationRecord[] = [
  {
    id: "c-today-001",
    doctorId: "doc-001",
    patient: {
      id: "p-001",
      name: "Arjun Mehta",
      age: 34,
      gender: "male",
      phone: "+91 98765 43210",
      email: "arjun.mehta@email.com",
      bloodGroup: "B+",
      allergies: ["Penicillin"],
    },
    date: "2026-06-14",
    startTime: "09:30",
    endTime: "09:45",
    mode: "video",
    status: "scheduled",
    symptoms: ["Fever since 2 days", "Headache", "Mild sore throat"],
    chiefComplaint: "Persistent fever with headache and sore throat for 2 days.",
    pastHistory: "No significant past medical history. Seasonal allergies in spring.",
    vitals: { bp: "118/76", pulse: "88", temp: "101.2°F", weight: "72 kg", height: "5'9\"" },
  },
  {
    id: "c-today-002",
    doctorId: "doc-001",
    patient: {
      id: "p-002",
      name: "Priya Sharma",
      age: 28,
      gender: "female",
      phone: "+91 91234 56789",
      email: "priya.sharma@email.com",
      bloodGroup: "O+",
      allergies: [],
    },
    date: "2026-06-14",
    startTime: "11:00",
    endTime: "11:15",
    mode: "chat",
    status: "scheduled",
    symptoms: ["Lower back pain", "Fatigue"],
    chiefComplaint: "Lower back pain radiating to left leg with general fatigue for 1 week.",
    pastHistory: "Mild lumbar spondylosis noted on X-ray 1 year ago.",
    vitals: { bp: "112/70", pulse: "76", weight: "58 kg", height: "5'4\"" },
  },
  {
    id: "c-today-003",
    doctorId: "doc-001",
    patient: {
      id: "p-003",
      name: "Ravi Kumar",
      age: 52,
      gender: "male",
      phone: "+91 99887 76655",
      email: "ravi.kumar@email.com",
      bloodGroup: "A+",
      allergies: ["Sulfa drugs", "Aspirin"],
    },
    date: "2026-06-14",
    startTime: "08:00",
    endTime: "08:15",
    mode: "video",
    status: "completed",
    symptoms: ["High BP", "Dizziness"],
    chiefComplaint: "Elevated blood pressure readings at home, feeling dizzy in mornings.",
    pastHistory: "Hypertension since 2018, on Amlodipine 5mg. Diabetes Type 2 since 2020.",
    vitals: { bp: "158/92", pulse: "82", temp: "98.6°F", weight: "88 kg", height: "5'7\"" },
    clinicalNotes: "BP elevated. Advised to increase Amlodipine to 10mg. Review in 2 weeks.",
    followUpDate: "2026-06-28",
  },
];

export const UPCOMING_CONSULTATIONS: ConsultationRecord[] = [
  {
    id: "c-upcoming-001",
    doctorId: "doc-001",
    patient: {
      id: "p-004",
      name: "Sneha Patel",
      age: 23,
      gender: "female",
      phone: "+91 87654 32109",
      email: "sneha.patel@email.com",
      bloodGroup: "AB+",
    },
    date: "2026-06-15",
    startTime: "10:00",
    endTime: "10:15",
    mode: "video",
    status: "scheduled",
    symptoms: ["Skin rash", "Itching"],
    chiefComplaint: "Itchy rash on forearms and neck appearing after new skincare product use.",
  },
  {
    id: "c-upcoming-002",
    doctorId: "doc-001",
    patient: {
      id: "p-005",
      name: "Mohammed Rafiq",
      age: 45,
      gender: "male",
      phone: "+91 76543 21098",
      bloodGroup: "B-",
    },
    date: "2026-06-16",
    startTime: "14:30",
    endTime: "14:45",
    mode: "chat",
    status: "scheduled",
    symptoms: ["Chest tightness", "Shortness of breath on exertion"],
    chiefComplaint: "Intermittent chest tightness and dyspnea on exertion since 3 days.",
  },
  {
    id: "c-upcoming-003",
    doctorId: "doc-001",
    patient: {
      id: "p-006",
      name: "Lakshmi Iyer",
      age: 61,
      gender: "female",
      phone: "+91 65432 10987",
      email: "lakshmi.iyer@gmail.com",
      bloodGroup: "O-",
      allergies: ["Codeine"],
    },
    date: "2026-06-17",
    startTime: "09:00",
    endTime: "09:15",
    mode: "video",
    status: "scheduled",
    symptoms: ["Joint pain", "Morning stiffness"],
    chiefComplaint: "Bilateral knee joint pain with morning stiffness lasting over 1 hour.",
  },
  {
    id: "c-upcoming-004",
    doctorId: "doc-001",
    patient: {
      id: "p-007",
      name: "Amit Verma",
      age: 38,
      gender: "male",
      phone: "+91 54321 09876",
      bloodGroup: "A-",
    },
    date: "2026-06-18",
    startTime: "16:00",
    endTime: "16:15",
    mode: "video",
    status: "scheduled",
    symptoms: ["Persistent cough", "Night sweats"],
    chiefComplaint: "Dry cough for 3 weeks with occasional night sweats. No fever.",
  },
];

export const PAST_CONSULTATIONS: ConsultationRecord[] = [
  {
    id: "c-past-001",
    doctorId: "doc-001",
    patient: {
      id: "p-008",
      name: "Deepika Nair",
      age: 31,
      gender: "female",
      phone: "+91 43210 98765",
      email: "deepika.nair@email.com",
      bloodGroup: "B+",
    },
    date: "2026-06-13",
    startTime: "10:30",
    endTime: "10:45",
    mode: "video",
    status: "completed",
    symptoms: ["Migraine", "Light sensitivity"],
    chiefComplaint: "Severe unilateral headache with photophobia, 3rd episode this month.",
    clinicalNotes: "Migraine with aura. Prescribed Sumatriptan 50mg. Lifestyle modifications advised.",
    followUpDate: "2026-07-01",
  },
  {
    id: "c-past-002",
    doctorId: "doc-001",
    patient: {
      id: "p-009",
      name: "Karthik Subramanian",
      age: 42,
      gender: "male",
      phone: "+91 32109 87654",
      bloodGroup: "O+",
      allergies: ["Ibuprofen"],
    },
    date: "2026-06-12",
    startTime: "11:30",
    endTime: "11:45",
    mode: "chat",
    status: "completed",
    symptoms: ["Acid reflux", "Bloating"],
    chiefComplaint: "Heartburn and bloating after meals, worsening over 2 weeks.",
    clinicalNotes: "GERD. Started on PPI. Dietary modifications counselled.",
  },
  {
    id: "c-past-003",
    doctorId: "doc-001",
    patient: {
      id: "p-010",
      name: "Ananya Krishnan",
      age: 25,
      gender: "female",
      phone: "+91 21098 76543",
      email: "ananya.k@email.com",
      bloodGroup: "A+",
    },
    date: "2026-06-11",
    startTime: "15:00",
    endTime: "15:15",
    mode: "video",
    status: "cancelled",
    symptoms: ["Anxiety", "Insomnia"],
    chiefComplaint: "Anxiety attacks and difficulty sleeping, exam stress related.",
  },
  {
    id: "c-past-004",
    doctorId: "doc-001",
    patient: {
      id: "p-011",
      name: "Suresh Reddy",
      age: 57,
      gender: "male",
      phone: "+91 10987 65432",
      bloodGroup: "B+",
      allergies: [],
    },
    date: "2026-06-10",
    startTime: "09:30",
    endTime: "09:45",
    mode: "video",
    status: "completed",
    symptoms: ["Diabetes check-up", "Foot numbness"],
    chiefComplaint: "Routine diabetes follow-up with new complaint of tingling in feet.",
    clinicalNotes: "HbA1c 8.2%. Peripheral neuropathy. Adjusted metformin dose. Vitamin B12 added.",
    followUpDate: "2026-07-10",
  },
  {
    id: "c-past-005",
    doctorId: "doc-001",
    patient: {
      id: "p-012",
      name: "Rekha Joshi",
      age: 48,
      gender: "female",
      phone: "+91 09876 54321",
      email: "rekha.joshi@email.com",
      bloodGroup: "AB-",
    },
    date: "2026-06-08",
    startTime: "13:00",
    endTime: "13:15",
    mode: "chat",
    status: "no-show",
    symptoms: ["Thyroid issues"],
    chiefComplaint: "Thyroid follow-up, feeling tired and cold frequently.",
  },
];

export const ALL_CONSULTATIONS: ConsultationRecord[] = [
  ...TODAY_CONSULTATIONS,
  ...UPCOMING_CONSULTATIONS,
  ...PAST_CONSULTATIONS,
];

export function getConsultationById(id: string): ConsultationRecord | undefined {
  return ALL_CONSULTATIONS.find((c) => c.id === id);
}
