"use client";

import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { useParams, useRouter } from "next/navigation";
import { doc, getDoc } from "firebase/firestore";
import { FaArrowLeft, FaPrint, FaWhatsapp, FaPrescriptionBottleAlt } from "react-icons/fa";
import { db } from "@/lib/firebase-db";
import { auth } from "@/lib/firebase-auth";
import { Button } from "@/components/ui/Button";
import type { Consultation, Prescription, PrescriptionMedicine } from "@/types/consultation";

export default function PatientPrescriptionPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();

  const [consultation, setConsultation] = useState<Consultation | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const uid = auth.currentUser?.uid;
      if (!uid) {
        router.replace("/login");
        return;
      }
      try {
        const snap = await getDoc(doc(db, "Consultations", params.id));
        if (cancelled) return;
        if (!snap.exists()) {
          setError("Consultation not found.");
          return;
        }
        const data = snap.data() as Consultation;
        if (!data.participants?.includes(uid)) {
          setError("You don't have access to this prescription.");
          return;
        }
        setConsultation(data);
      } catch {
        if (!cancelled) setError("Couldn't load this prescription. Try again.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [params.id, router]);

  const prescription: Prescription | undefined = consultation?.prescription;
  const patientDetails = consultation?.extras?.patientDetails;
  const today = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const buildWhatsAppText = () => {
    if (!prescription) return "";
    const pName = patientDetails?.patientName ?? prescription.patientName ?? "Patient";
    const pAge = patientDetails?.patientAge ?? prescription.patientAge ?? "";
    const lines: string[] = [
      `*Prescription from Soocher*`,
      `Doctor: ${consultation?.doctorName ?? "—"}`,
      `Patient: ${pName}${pAge ? `, ${pAge} yrs` : ""}`,
      `Date: ${prescription.date ?? today}`,
      `Diagnosis: ${prescription.diagnosis ?? "—"}`,
      ``,
      `*Medicines:*`,
      ...(prescription.medicines ?? []).map(
        (m: PrescriptionMedicine) => `• ${m.name} | ${m.dose} | ${m.frequency} | ${m.duration}${m.instructions ? ` (${m.instructions})` : ""}`
      ),
      ``,
      prescription.advice ? `*Advice:* ${prescription.advice}` : "",
      prescription.followUpDate ? `*Follow-up:* ${new Date(prescription.followUpDate).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}` : "",
      ``,
      `_Generated by Soocher_`,
    ].filter(Boolean);
    return encodeURIComponent(lines.join("\n"));
  };

  const handlePrint = () => window.print();
  const handleWhatsApp = () => window.open(`https://wa.me/?text=${buildWhatsAppText()}`, "_blank");

  if (loading) {
    return (
      <div className="grid min-h-[100dvh] place-items-center bg-[#F5F8FD]">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" />
      </div>
    );
  }

  if (error || !prescription) {
    return (
      <div className="mx-auto min-h-[100dvh] max-w-2xl bg-[#F5F8FD] px-4 py-16 text-center">
        <div className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-3xl bg-slate-100 text-slate-400">
          <FaPrescriptionBottleAlt className="text-2xl" />
        </div>
        <h2 className="text-lg font-bold text-slate-900">{error ? "Couldn't open prescription" : "No prescription found"}</h2>
        <p className="mt-1 text-sm text-slate-500">{error ?? "This consultation doesn't have a saved prescription yet."}</p>
        <button
          onClick={() => router.back()}
          className="mx-auto mt-5 flex items-center gap-2 text-sm font-semibold text-primary transition hover:text-primary-600"
        >
          <FaArrowLeft className="text-xs" /> Back
        </button>
      </div>
    );
  }

  const medicines: PrescriptionMedicine[] = prescription.medicines ?? [];

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white; }
          .print-page { box-shadow: none !important; border: none !important; max-width: 100% !important; }
        }
      `}</style>

      <div className="min-h-[100dvh] bg-[#F5F8FD] px-4 pb-12 pt-4 md:px-6">
        <div className="mx-auto max-w-2xl">
          {/* Action buttons — hidden on print */}
          <div className="no-print mb-5 flex items-center gap-3" style={{ paddingTop: "env(safe-area-inset-top, 0px)" }}>
            <button
              onClick={() => router.back()}
              className="hidden items-center gap-2 text-sm font-semibold text-slate-600 transition hover:text-primary md:flex"
            >
              <FaArrowLeft className="text-xs" /> Back
            </button>
            <div className="flex-1" />
            <Button
              variant="bordered"
              size="sm"
              className="rounded-full border-2 border-slate-200 font-semibold"
              startContent={<FaWhatsapp className="text-emerald-500" />}
              onClick={handleWhatsApp}
            >
              Share
            </Button>
            <Button
              color="primary"
              size="sm"
              className="rounded-full font-semibold shadow-lg shadow-primary/25"
              startContent={<FaPrint />}
              onClick={handlePrint}
            >
              Print / PDF
            </Button>
          </div>

          {/* Prescription card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="print-page rounded-3xl border border-slate-200 bg-white p-6 shadow-lg shadow-primary/10 md:p-8"
          >
            {/* Header */}
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="text-2xl font-black tracking-tight text-primary">Soocher</div>
                <div className="text-xs font-semibold text-slate-400">Prescription</div>
              </div>
              <div className="text-right">
                <p className="font-black tracking-tight text-slate-900">{consultation?.doctorName ?? "—"}</p>
                <p className="text-xs text-slate-400">{prescription.date ?? today}</p>
              </div>
            </div>

            <div className="my-5 h-px bg-slate-100" />

            {/* Patient info */}
            <div className="mb-5 grid grid-cols-2 gap-4 rounded-2xl bg-slate-50 p-4 md:grid-cols-4">
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Patient</p>
                <p className="mt-0.5 text-sm font-bold text-slate-900">{patientDetails?.patientName ?? prescription.patientName ?? "—"}</p>
              </div>
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Age</p>
                <p className="mt-0.5 text-sm font-bold text-slate-900">{patientDetails?.patientAge ?? prescription.patientAge ?? "—"} yrs</p>
              </div>
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Gender</p>
                <p className="mt-0.5 text-sm font-bold capitalize text-slate-900">{patientDetails?.gender ?? "—"}</p>
              </div>
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Date</p>
                <p className="mt-0.5 text-sm font-bold text-slate-900">{prescription.date ?? today}</p>
              </div>
            </div>

            {/* Diagnosis */}
            {prescription.diagnosis && (
              <div className="mb-5">
                <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Diagnosis</p>
                <p className="mt-1 text-base font-bold text-slate-900">{prescription.diagnosis}</p>
              </div>
            )}

            <div className="my-5 h-px bg-slate-100" />

            {/* Rx */}
            <div className="mb-5">
              <div className="mb-3 flex items-center gap-2">
                <span className="text-4xl font-black text-primary" style={{ fontFamily: "serif" }}>℞</span>
                <span className="font-black tracking-tight text-slate-900">Medicines</span>
              </div>

              {medicines.length === 0 ? (
                <p className="text-sm text-slate-400">No medicines added.</p>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-slate-100">
                        <th className="pb-2 text-left text-[10px] font-semibold uppercase tracking-widest text-slate-400">#</th>
                        <th className="pb-2 text-left text-[10px] font-semibold uppercase tracking-widest text-slate-400">Medicine</th>
                        <th className="pb-2 text-left text-[10px] font-semibold uppercase tracking-widest text-slate-400">Dose</th>
                        <th className="pb-2 text-left text-[10px] font-semibold uppercase tracking-widest text-slate-400">Frequency</th>
                        <th className="pb-2 text-left text-[10px] font-semibold uppercase tracking-widest text-slate-400">Duration</th>
                      </tr>
                    </thead>
                    <tbody>
                      {medicines.map((m: PrescriptionMedicine, i: number) => (
                        <tr key={m.id} className="border-b border-slate-50">
                          <td className="py-2.5 pr-3 text-slate-400">{i + 1}</td>
                          <td className="py-2.5 pr-3 font-semibold text-slate-900">
                            {m.name}
                            {m.instructions && (
                              <span className="mt-0.5 block text-xs font-normal text-slate-400">{m.instructions}</span>
                            )}
                          </td>
                          <td className="py-2.5 pr-3 text-slate-600">{m.dose || "—"}</td>
                          <td className="py-2.5 pr-3 text-slate-600">{m.frequency || "—"}</td>
                          <td className="py-2.5 text-slate-600">{m.duration || "—"}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Advice */}
            {prescription.advice && (
              <>
                <div className="my-4 h-px bg-slate-100" />
                <div className="mb-4">
                  <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">Advice / Instructions</p>
                  <p className="mt-1 text-sm leading-relaxed text-slate-700">{prescription.advice}</p>
                </div>
              </>
            )}

            {/* Follow-up */}
            {prescription.followUpDate && (
              <div className="mb-4 rounded-xl bg-primary-50 px-4 py-3">
                <p className="text-xs font-semibold text-primary">
                  Follow-up on:{" "}
                  <span className="font-black">
                    {new Date(prescription.followUpDate).toLocaleDateString("en-IN", {
                      weekday: "short",
                      day: "numeric",
                      month: "long",
                      year: "numeric",
                    })}
                  </span>
                </p>
              </div>
            )}

            <div className="mt-6 flex items-center justify-between text-[10px] text-slate-400">
              <span>{prescription.date ?? today}</span>
              <span>Ref #{params.id.slice(0, 10).toUpperCase()}</span>
            </div>
          </motion.div>
        </div>
      </div>
    </>
  );
}
